<?php
/**
 * Created by PhpStorm.
 * User: Mikou.hu
 * Date: 2018/9/11
 */

namespace app\admin\controller;

use gmars\rbac\Rbac;
use think\Controller;
use think\Db;
use think\Request;

class Permission extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $css = config('style_path.admin_css_path');
        $js = config('style_path.admin_js_path');
        $img = config('style_path.admin_img_path');
        $picture = config('style_path.admin_picture_path');
        $this->assign(array(
            'css' => $css,
            'js' => $js,
            'img' => $img,
            'picture' => $picture
        ));
    }

    public function index()
    {
        return view('admin@permission/index');
    }

    public function getList(Request $request)
    {
        $data = $request->post();
        $current_page = $data['current_page'];
        $pagesize = 10;
        $start = ($current_page - 1) * $pagesize;
        $list = Db::name('permission')->field('id,name,path,description,status')->limit($start, $pagesize)->select();
        $count = Db::name('permission')->count();
        $this->ajaxReturnMsg(200, 'success', array('list' => $list, 'count' => ceil($count / $pagesize)));
    }

    public function insert(Request $request)
    {
        $input = $request->post();
        $data = json_decode($input['msg'], true);

        if (!isset($data['name']) || empty($data['name']) || !isset($data['path']) || empty($data['path']) || !isset($data['description']) || empty($data['description']) || !isset($data['status'])) {
            $this->ajaxReturnMsg(201, '参数错误', '');
        }

        // 判断用户是否存在
        if (Db::name('permission')->where('name', $data['name'])->count()) {
            $this->ajaxReturnMsg(202, '权限已存在', '');
        }

        // 判断手机号是否存在
        if (Db::name('permission')->where('path', $data['path'])->count()) {
            $this->ajaxReturnMsg(202, '权限路径已存在', '');
        }
        //判断邮箱是否存在

        //加密
        $param = array(
            'name'  => $data['name'],
            'path'  => $data['path'],
            'create_time' => date("Y-m-d H:i:s")
        );

        $id = Db::name('permission')->insertGetId($param);
        $this->ajaxReturnMsg(200, 'success', $id);

    }

    public function edit(Request $request)
    {

        $input = $request->post();
        $data = json_decode($input['msg'], true);

        if (!isset($data['name']) || empty($data['name']) || !isset($data['path']) || empty($data['path']) || !isset($data['description']) || empty($data['description']) || !isset($data['status'])) {
            $this->ajaxReturnMsg(201, '参数错误', '');
        }


        // 判断用户是否存在
        if (Db::name('permission')->where('id', '<>', $data['id'])->where('name', $data['name'])->count()) {
            $this->ajaxReturnMsg(202, '用户名已存在', '');
        }

        if (Db::name('permission')->where('id', '<>', $data['id'])->where('path', $data['name'])->count()) {
            $this->ajaxReturnMsg(202, '用户名已存在', '');
        }
        $param = $data;
        Db::name('permission')->where('id', $data['id'])->update($param);
        $this->ajaxReturnMsg(200, 'success', '');

    }

    public function delete(Request $request)
    {
        $data = $request->post();
        if (!isset($data['id']) || empty($data['id'])) {
            $this->ajaxReturnMsg(201, '缺少参数', '');
        }
        $falg = Db::name('permission')->where('id', $data['id'])->count();
        if (!$falg) {
            $this->ajaxReturnMsg(201, '网络错误', '');
        }
        $rbac = new Rbac();
        $flag = $rbac->delPermission($data['id']);
        if (!$flag) $this->ajaxReturnMsg(202, '', '');
        $this->ajaxReturnMsg(200, 'success', '');
    }


}