<?php
/**
 * Created by PhpStorm.
 * User: Mikou.hu
 * Date: 2018/9/29
 */

namespace app\index\controller;


use think\Controller;
use think\Request;
use think\Session;
use think\Db;

class Center extends  Controller
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $css = config('style_path.css_path');
        $js = config('style_path.js_path');
        $img = config('style_path.img_path');
        $picture = config('style_path.picture_path');
        $this->assign(array(
            'css' => $css,
            'js' => $js,
            'img' => $img,
            'picture' => $picture,
            'on1' =>'',
            'on2' =>'',
            'on3' =>'',
            'on4' =>'',
            'on5' =>''
        ));

        $request = \think\Request::instance();
        if (!$user_msg = Session::get('member_user')) {
            if($request->post()){
                $this->ajaxReturnMsg('105', '请重新登录', '');
            }
            $this->redirect('/index/person/login');
        }
    }

    public function index()
    {
        $this->assign(array(
            'on1' => 'ddCur',
        ));
        return view('index@center/index');
    }

    public function getUser()
    {
       $user = Session::get('member_user');
       $data = Db::name('member')->alias('p1')
           ->field('p1.user,p1.cid,p2.name')
           ->join('company p2','p1.cid = p2.id','left')
           ->where('p1.id',$user['id'])
           ->where('p1.status',1)
           ->where('p1.deleted',0)
           ->where('p2.deleted',0)
           ->find();
       if(empty($data)){
       	Session::delete('member_user');
           $this->ajaxReturnMsg(105,'重新登录','');
       }
       $data['last_login_time'] = formatDate($user['last_login_time']);
        $data['ip'] = Request::instance()->ip();;//登录ip地址
       $this->ajaxReturnMsg(200,'success',$data);

    }
    public function pwd()
    {
        $this->assign(array(
            'on2' => 'ddCur',
        ));
        return view('index@center/pwd');
    }


    public function edit(Request $request)
    {
        $data = $request->post();
        if( !isset($data['old']) || empty($data['old']) || !isset($data['newpwd']) || empty($data['newpwd']) || !isset($data['renew']) || empty($data['renew']) ){
            $this->ajaxReturnMsg(201,'您有数据未输入','');
        }
        if(!(md5($data['newpwd']) === md5($data['renew']))){
            $this->ajaxReturnMsg(201,'两次密码输入不一致','');
        }

        if(!Db::name('member')->where('id',Session::get('member_user.id'))->where('deleted',0)->where('password',md5($data['old']))->count()){
            $this->ajaxReturnMsg(201,'旧密码错误','');
        }
        Db::name('member')->where('id',Session::get('member_user.id'))->where('deleted',0)->update(array('password'=>md5($data['newpwd'])));
        Session::delete('member_user');
        $this->ajaxReturnMsg(200,'success','');

    }

    public function log()
    {
        $this->assign(array(
            'on3' => 'ddCur',
        ));
        return view('index@center/log');
    }

    public function getlog(Request $request)
    {
        $data = $request->post();
        $current_page = $data['current_page'];
        $pagesize = 10;
        $start = ($current_page - 1) * $pagesize;
        $list = Db::name('login_log')->field('login_name,create_time,service_ip')->where('login_name',Session::get('member_user.user'))->where('source',1)->limit($start, $pagesize)->order('id','desc')->select();
        $count = Db::name('login_log')->where('login_name',Session::get('member_user.user'))->where('source',1)->count();
        $data = array(
            'list' => $list,
            'count' => ceil($count / $pagesize)
        );
        $this->ajaxReturnMsg(200,'success',$data);

    }

    public function order()
    {
        $this->assign(array(
            'on4' => 'ddCur',
        ));
        return view('index@center/order');
    }

    public function getOrder(Request $request)
    {
        $data = $request->post();
        $current_page = $data['current_page'];
        $pagesize = 10;
        $start = ($current_page - 1) * $pagesize;

        $condition['p1.deleted'] = ['=', '0'];
        if (isset($data['s_brj']) && !empty($data['s_brj'])) {
            $condition['p4.crj'] = ['=', $data['s_brj']];
        }

        if (isset($data['s_type']) && !empty($data['s_type'])) {
            $condition['p4.type'] = ['=', $data['s_type']];
        }

        if (isset($data['s_method']) && !empty($data['s_method'])) {
            $condition['p4.method'] = ['=', $data['s_method']];
        }


        if (isset($data['s_address']) && !empty($data['s_address'])) {
            $condition['p4.address'] = ['like', '%'.$data['s_address'].'%'];
        }

        if (isset($data['s_status']) && !empty($data['s_status'])) {
            $condition['p4.status'] = ['=', $data['s_status']];
        }
        if(isset($data['s_status']) && !empty($data['s_status'])){
            if($data['s_status']==3){
                unset($condition['p4.status']);
                $condition['p4.deleted'] = ['=', 1];
            }
        }

        if (isset($data['s_time']) && !empty($data['s_time'])) {
            $condition['p4.start_time'] = ['>=', $data['s_time']];
        }

        $condition['p1.id'] = ['=', Session::get('member_user.id')];
        $list = Db::name('member')
            ->alias('p1')
            ->field('
            p4.crj,
            p4.type,
            p5.name as type_name,
            p6.actual,
            p4.status,
            p4.address,
            p4.method,
            p4.price,
                 DATE_FORMAT(p4.start_time,"%Y-%m-%d") as start_time,
                     DATE_FORMAT(p4.end_time,"%Y-%m-%d") as end_time,
                     DATE_FORMAT(p4.teardown,"%Y-%m-%d") as teardown')
            ->join('company p2', 'p2.id = p1.cid', 'left')
            ->join('crj_code p3','p3.cid=p2.id','left')
            ->join('crj p4','p4.crj=p3.crj_code','left')
            ->join('service_type p5','p5.id = p4.type' ,'left')
            ->join('crj_bt p6','p6.crj_id=p4.id','left')

            ->where($condition)
            ->order('p4.id', 'desc')
            ->limit($start, $pagesize)
            ->select();
        $count =  Db::name('member')
            ->alias('p1')
            ->join('company p2', 'p2.id = p1.cid', 'left')
            ->join('crj_code p3','p3.cid=p2.id','left')
            ->join('crj p4','p4.crj=p3.crj_code','left')
            ->join('service_type p5','p5.id = p4.type' ,'left')
            ->join('crj_bt p6','p6.crj_id=p4.id','left')
            ->where($condition)
            ->order('p3.id', 'desc')
            ->count();
        $typeList = Db::name('service_type')->field('id,name,status')->select();
        $data = array(
            'list' => $list,
            'typelist'=>$typeList,
            'count' => ceil($count / $pagesize)
        );
        $this->ajaxReturnMsg(200,'success',$data);
    }

    public function note()
    {
        $this->assign(array(
            'on5' => 'ddCur',
        ));
        return view('index@center/note');
    }

    public function getNoteList(Request $request)
    {
        $data = $request->post();
        $current_page = $data['current_page'];
        $pagesize = 10;
        $start = ($current_page - 1) * $pagesize;
        $list =  Db::name('note')->field('id,content,status,create_time')
            ->where('member_id','=',Session::get('member_user.id'))
           ->order('id', 'desc')
            ->limit($start, $pagesize)
            ->select();
       $count = Db::name('note')->field('id,content,status,create_time')
           ->where('member_id','=',Session::get('member_user.id'))
           ->order('id', 'desc')
           ->count();
        $data = array(
            'list' => $list,
            'count' => ceil($count / $pagesize)
        );
        $this->ajaxReturnMsg(200,'success',$data);
    }


    public  function  sendnote(Request $request)
    {
        $data = $request->post();
        if(!isset($data['msg']) || empty($data['msg'])){
            $this->ajaxReturnMsg(201,'内容不能为空',$data);
        }

        $param =array(
            'member_id'     =>  Session::get('member_user.id'),
            'content'       =>  $data['msg'],
            'name'          =>  Session::get('member_user.user'),
            'ip'            =>  $request->ip(),
            'status'        => 0,
            'create_time'   =>  date('Y-m-d H:i:s')
        );

        Db::name('note')->insert($param);

        $this->ajaxReturnMsg(200,'success',$data);

    }

    public function getDetail(Request $request)
    {
        $data = $request->post();

        if(!isset($data['id']) || empty($data['id']) ){
            $this->ajaxReturnMsg(201, '参数错误 ', '');
        }
        $topic = Db::name('note')->field('content,create_time,name')->where('id',$data['id'])->find();
        $topic['create_time'] = formatDate($topic['create_time']);

        $list = Db::name('note_comment')
            ->field('user_name,content,create_time,source')
            ->where('note_id',$data['id'])
            ->order('id','asc')
            ->select();
        foreach ($list as $k => $v){
            $list[$k]['create_time'] = formatDate($v['create_time']);
        }
        $res = array(
            'topic' => $topic,
            'list' => $list,
        );
        $this->ajaxReturnMsg(200, 'success', $res);
    }


    public function sendNew(Request $request)
    {
        $data = $request->post();

        if(!isset($data['id']) || empty($data['id']) || !isset($data['msg']) || empty($data['msg']) ){
            $this->ajaxReturnMsg(201, '参数错误 ', '');
        }
        $param = array(
            'note_id'        => $data['id'],
            'content'        => $data['msg'],
            'source'         => 1,
            'ip'             =>$request->ip(),
            'user_name'          =>  Session::get('member_user.user'),
            'user_id'        =>Session::get('member_user.id'),
            'create_time'    => date("Y-m-d H:i:s")
        );
        Db::name('note_comment')->insert($param);
        Db::name('note')->where('id',$data['id'])->update(['status'=>0]);
        $this->ajaxReturnMsg(200, 'success', '');
    }

    protected function ajaxReturnMsg($code = 200, $msg, $data, $api_id = 0)
    {
        //        $this->api->end($api_id,$code,$msg,$data);
        header('Access-Control-Allow-Origin: *');//跨域
        header('Content-type: application/json');
        echo json_encode(array('code' => $code, 'msg' => $msg, 'data' => $data));
        die;
    }


}