<?php

namespace app\index\controller;

use think\Controller;
use think\Request;
use think\config;

class Index extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $css = config('style_path.css_path');
        $js = config('style_path.js_path');
        $img = config('style_path.img_path');
        $picture = config('style_path.picture_path');
        $this->assign(array(
            'css' => $css,
            'js' => $js,
            'img' => $img,
            'picture' => $picture
        ));
    }

    /**首页
     * @return \think\response\View
     */
    public function index()
    {
        return view('index@index/index');
    }


    public function about()
    {
        return view('index@index/about');
    }

    public function connect()
    {
        return view('index@index/connect');
    }

    public function example()
    {
        return view('index@index/example');
    }

}
