<?php

namespace app\index\controller;

use Think\Cache;
use think\Controller;
use think\Request;
use think\config;
use think\Db;

class Index extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $css = config('style_path.css_path');
        $js = config('style_path.js_path');
        $img = config('style_path.img_path');
        $picture = config('style_path.picture_path');
        $this->assign(array(
            'css' => $css,
            'js' => $js,
            'img' => $img,
            'picture' => $picture,
            'on1' =>'',
            'on2' =>'',
            'on3' =>'',
            'on4' =>'',
        ));
    }

    /**首页
     * @return \think\response\View
     */
    public function index()
    {
        $this->visitLog();
        return view('index@index/index');
    }


    public function  product()
    {
        $this->assign(array(
            'on1' => 'on',
        ));
        return view('index@index/product');
    }
    public function example()
    {
        $this->assign(array(
            'on2' => 'on',
        ));
        return view('index@index/example');
    }

    public function about()
    {
        $this->assign(array(
            'on3' => 'on',
        ));
        return view('index@index/about');
    }

    public function connect()
    {
        $this->assign(array(
            'on4' => 'on',
        ));
        return view('index@index/connect');
    }

    public function test(Request $request)
    {
        $param = array(
            'ip' => $request->ip(),
            'time'=> date("Y-m-d H:i:s")
        );
        Db::name('test')->insert($param);
    }


    private function visitLog()
    {
        $ip = Request::instance()->ip();
        $cache = cache('visit_index_'.$ip.'_');
        if(!$cache){
            Db::name('visit')->insert(
                array(
                    'ip' => $ip,
                    'create_time' => date('Y-m-d H:i:s')
                )
            );
            cache('visit_index_'.$ip.'_',$ip,['expire'=>1800] );
        }
    }

}
