<?php
/**
 * Created by PhpStorm.
 * User: Mikou
 * Date: 2018/9/28 0028
 * Time: 20:58
 */

namespace app\index\controller;

use think\Controller;
use think\Request;
use think\config;

class Person extends  Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $css = config('style_path.css_path');
        $js = config('style_path.js_path');
        $img = config('style_path.img_path');
        $picture = config('style_path.picture_path');
        $this->assign(array(
            'css' => $css,
            'js' => $js,
            'img' => $img,
            'picture' => $picture,
            'on1' =>'',
            'on2' =>'',
            'on3' =>'',
            'on4' =>'',


        ));
    }


    public function login()
    {
        return view('index@person/login');
    }

    public function message()
    {
        return view('index@person/message');
    }

}